name: phone_recap
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter

  call_log: ^4.0.0
  bloc: ^9.0.0
  url_launcher: ^6.3.1
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
