name: phone_recap
description: "Phone Recap is a simple app that helps you keep track of your phone calls."
publish_to: "none"
version: 1.1.9+14

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  call_log:
    path: packages/call_log
  flutter_bloc: ^9.1.0
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.2
  equatable: ^2.0.7
  shimmer: ^3.0.0
  package_info_plus: ^8.3.0
  flutter_local_notifications: ^19.0.0
  permission_handler: ^11.4.0
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  flutter_contacts: ^1.1.9+2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
