name: phone_recap
description: "Phone Recap is a simple app that helps you keep track of your phone calls."
publish_to: "none"
version: 1.0.2+3

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  call_log: ^4.0.0
  bloc: ^9.0.0
  url_launcher: ^6.3.1
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.1
  google_mobile_ads: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
