name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    if: startsWith(github.event.head_commit.message, 'version')
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        # Needed for full commit history
        # with:
        #   fetch-depth: 0

      - name: Extract App Version
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | sed -E 's/version: ([0-9]+\.[0-9]+\.[0-9]+)\+?[0-9]*/\1/')
          echo "APP_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version: 3.29.0

      - name: Cache Flutter dependencies
        id: flutter-pub-cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.FLUTTER_HOME }}/.pub-cache/
            .dart_tool/
          key: ${{ runner.os }}-flutter-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-pub-

      - name: Cache Gradle
        id: gradle-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.caching=true

      - name: Generate Changelog
        id: changelog
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            git log --pretty=format:"- %s (%h) [%an]" > CHANGELOG.md
          else
            git log --pretty=format:"- %s (%h) [%an]" $PREV_TAG..HEAD >> CHANGELOG.md
          fi
          echo "CHANGELOG_PATH=CHANGELOG.md" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.APP_VERSION }}
          name: Release ${{ steps.version.outputs.APP_VERSION }}
          files: build/app/outputs/flutter-apk/app-release.apk
          body_path: ${{ steps.changelog.outputs.CHANGELOG_PATH }}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
