name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      # - name: Set up Java
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: "zulu"
      #     java-version: "17"
      # - name: Set up Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     cache: true
      #     channel: stable
      #     flutter-version: 3.29.0
      # - name: Install dependencies
      #   run: flutter pub get
      # - name: Build APK
      #   run: flutter build apk
      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # files: build/app/outputs/flutter-apk/app-release.apk
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          repository: my_gh_org/my_gh_repo
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
