name: Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.6"
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:"
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-x86_64-release.apk
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: This is the release of the APK built from commit ${{ github.sha }}.
