name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: List packages directory
        run: ls -l
      # - name: Set up Java
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: "zulu"
      #     java-version: "17"
      # - name: Set up Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     cache: true
      #     channel: stable
      #     flutter-version: 3.29.0
      # - run: flutter pub get
      # - run: flutter build apk
      # - name: Print outputs
      #   shell: bash
      #   run: |
      #     echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
      #     echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
      #     echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
      #     echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
      #     echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
      #     echo PUB-CACHE-PATH=${{ steps.flutter-action.outputs.PUB-CACHE-PATH }}
      #     echo PUB-CACHE-KEY=${{ steps.flutter-action.outputs.PUB-CACHE-KEY }}
